# Based on GTSAM file (by @ProfFan)
name: CI Linux

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.name }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}

    env:
      CTEST_OUTPUT_ON_FAILURE: ON
      CTEST_PARALLEL_LEVEL: 1
      CMAKE_BUILD_TYPE: ${{ matrix.build_type }}
      VERBOSE: 1  # to show all cmake scripts debug info

    strategy:
      fail-fast: false
      matrix:
        # Github Actions requires a single row to be added to the build matrix.
        # See https://help.github.com/en/articles/workflow-syntax-for-github-actions.
        name: [
          ubuntu-22.04-gcc,
          ubuntu-latest-gcc
        ]

        build_type: [ Release ]
        include:
          - name: ubuntu-20.04-gcc
            os: ubuntu-20.04
            compiler: gcc
            coverage: OFF
            
          - name: ubuntu-latest-gcc
            os: ubuntu-latest
            compiler: gcc
            coverage: OFF

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y upgrade
          sudo apt-get install -y cmake \
                                  libgoogle-glog-dev \
                                  libgflags-dev \
                                  libatlas-base-dev \
                                  libeigen3-dev \
                                  libsuitesparse-dev 
          git clone https://ceres-solver.googlesource.com/ceres-solver
          cd ceres-solver && mkdir build && cd build
          cmake .. && make && sudo make install
#          cd ../.. && rm -rf ceres-solver
          git clone https://github.com/miguelcastillon/fgt_threshold
          cd fgt_threshold && mkdir build && cd build
          cmake .. && make && sudo make install
#          cd ../.. && rm -rf fgt_threshold
      - name: Build
        run: |
          mkdir build && cd build
          cmake .. && make -j2
      - name: Test
        run: |
          ctest -j2

                                            