# Based on GTSAM file (by @ProfFan)
name: CI Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt -y update
          sudo apt -y upgrade
          sudo apt install -y git \
                              openssh-client \
                              libgoogle-glog-dev \
                              libgflags-dev \
                              libgtest-dev \
                              libatlas-base-dev \
                              libeigen3-dev \
                              libsuitesparse-dev 
      - name: Install CMake 2.24.2
        run: |
          wget https://github.com/Kitware/CMake/releases/download/v3.24.2/cmake-3.24.2.tar.gz
          tar -zxvf cmake-3.24.2.tar.gz
          cd cmake-3.24.2
          ./bootstrap --prefix=$HOME/cmake-install
          make -j2
          sudo make install
          export PATH=$HOME/cmake-install/bin:$PATH
          export CMAKE_PREFIX_PATH=$HOME/cmake-install:$CMAKE_PREFIX_PATH
      - name: Install Eigen 3.4
        run: |
          wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz
          tar -zxvf eigen-3.4.0.tar.gz
          cd eigen-3.4.0 && mkdir build && cd build
          cmake .. && make -j2 && sudo make install
          sudo ln -sf /usr/local/include/eigen3/Eigen /usr/local/include/Eigen
          sudo ln -sf /usr/local/include/eigen3/unsupported /usr/local/include/unsupported
          cd ../..
      - name: Install Ceres
        run: |
          git clone https://ceres-solver.googlesource.com/ceres-solver
          cd ceres-solver && mkdir build && cd build
          cmake -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF .. && make -j2 && sudo make install
          cd ../..
      - name: Install FGT
        run: |
          git clone https://github.com/miguelcastillon/fgt_threshold
          cd fgt_threshold && mkdir build && cd build
          cmake .. && make -j2 && sudo make install
          cd ../..
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          mkdir build && cd build
          cmake -DBUILD_TESTS=ON ..
          make
      - name: Test
        run: |
          ctest                                            